bridge:
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:String
    topic_from: /status/scara
    topic_to: sdk/test/scara
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:String
    topic_from: sdk/test/scara
    topic_to: /status
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:Bool
    topic_from: /ping
    topic_to: sdk/test/Python
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:Bool
    topic_from: sdk/test/Python
    topic_to: /pong
mqtt: 
  connection: 
    host: a1ahmtv2bnhf50-ats.iot.us-east-1.amazonaws.com
    port: 8883
    keepalive: 60
    mode: both
  client: 
    clientId: basicPubSub
    protocol: 4
    websocket : False
tls: 
  rootCA: /home/dftossem/Documents/aws/iot/connect_device_package/root-CA.crt
  certKey: /home/dftossem/Downloads/c35c934f0c-certificate.pem.crt
  privKey: /home/dftossem/Downloads/c35c934f0c-private.pem.key
