bridge:
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:String
    topic_from: /machine/logger
    topic_to: logger/machine
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:Bool
    topic_from: /machine/available
    topic_to: logger/machine/available
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: geometry_msgs.msg:Twist
    topic_from: sumerian/bochica/twist
    topic_to: /turtle1/cmd_vel
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:Bool
    topic_from: sumerian/bochica/bool
    topic_to: /local/bochica/bool
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: geometry_msgs.msg:Point
    topic_from: sumerian/bochica/point
    topic_to: /local/bochica/point
mqtt: 
  connection: 
    host: a1ahmtv2bnhf50-ats.iot.us-east-1.amazonaws.com
    port: 8883
    keepalive: 60
    mode: both
  client: 
    clientId: basicPubSub
    protocol: 4
    websocket : False
tls: 
  rootCA: /home/dftossem/Documents/aws/credentials/dummy/root-CA.crt
  certKey: /home/dftossem/Documents/aws/credentials/dummy/c35c934f0c-certificate.pem.crt
  privKey: /home/dftossem/Documents/aws/credentials/dummy/c35c934f0c-private.pem.key
